#!/usr/bin/env bash

i=1
while [ $i -le 31 ]
do
  for j in 1 2 3 4 5
    do
      timeout -s SIGINT 10 perf stat -e cycles,instructions ./unroll_write_reg $i  &>> IPC_reg.txt
      echo $j >> IPC_reg.txt
    done
  echo $i &>> IPC_reg.txt
  i=$(( $i + 1 ))
done

