#!/usr/bin/env bash

if [[ $# -eq 0 ]] ; then
    echo "Must pass in file heading or 'all'"
    exit 1
fi

input=$1

:> write_to.txt

if [[ "$input" = "all" ]]
then
  declare -a arr=("io" "reg" "io_poll")
else
  declare -a arr=("$input")
fi

for file in "${arr[@]}"
do
  for i in $(seq 1 30)
  do
    for j in $(seq 1 5)
    do 
      echo -n $i,$j, >> ./stats/IPC/${file}.txt 
      grep 'ins' <(timeout -s SIGINT 10 perf stat ./programs/IPC/${file} $i 2>&1 ) | cut -d '#' -f 2 | awk '{printf $1}' >> ./stats/IPC/${file}.txt
      echo ""  >> ./stats/IPC/${file}.txt
    done
  done
  :> write_to.txt
done


